server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  accessKey: ${MINIO_ACCESS_KEY:dummyaccess}
  secretKey: ${MINIO_SECRET_KEY:dummysecret123}
  bucketName: ${MINIO_BUCKET_NAME:weblog}

lucene:
  indexDir: ${LUCENE_INDEX_DIR:/app/weblog/lucene-index}

weblog:
  upload:
    local-dir: ${LOCAL_UPLOAD_DIR:/app/weblog/uploaded-files}

logging:
  config: classpath:logback-weblog.xml
